### PR TITLE
Add support for uv as package manager

### PR DESCRIPTION
**Pull request by mads-oestergaard**
This PR addresses https://github.com/allegroai/clearml-agent/issues/214 by supporting uv as package manager similar to how it's done for poetry today. 

It does not change the default behaviour of pip, although that could also be done. 

I have a single TODO that I'm unsure of. In commands/worker.py, line 3457, I would like to set UV_PROJECT_ENVIRONMENT to the current venv cache dir. What should that be?

### CODE REVIEW

**Comment by mads-oestergaard** [comment]
Updated the PR. 

I now choose the cache dir to point to the agent.venvs_dir path. That *should* ensure that venvs are cached between invocations. UV creates a .venv dir in the root of the project, so that's also accounted. for. 

@jkhenning @bmartinn  for visibility.

**Comment by Ruhrozz** [comment]
Why is it not merged yet =(

**Comment by mads-oestergaard** [comment]
No clue. I've asked on slack, but it seems like the team is busy with other things

**Comment by casperthuis** [comment]
Please merge this.

**Comment by jkhenning** [comment]
Hi all, we're currently testing this a bit and will merge it, probably on Monday

**Comment by noamsgl** [comment]
Is this included in an official release yet?

**Pull request merged**
