### PR TITLE
Fix agent update version

### PR DESCRIPTION
**Pull request by achaiah**
Pip install command is missing the '=='  to execute successfully

### CODE REVIEW

**Comment by jkhenning** [comment]
Hi @achaiah,

Thanks for your contribution!
Actually, the current implementation has its rational - it allows you to specify both exact versions (by setting `CLEARML_AGENT_UPDATE_VERSION="==1.2.3"` as well as other constraints (e.g. `CLEARML_AGENT_UPDATE_VERSION="<=1.2.3"`)

**Comment by achaiah** [comment]
Hmm... this is an "interesting" solution as I wouldn't have expected this format when providing an ENV variable. What's worse, it doesn't really produce any errors when you simply provide the version without the "==" which is what threw me for a loop in the first place. 

I expected to be able to provide just the version number.  Is this behavior documented anywhere? I had to dig through the source code to figure it out but I'm new to ClearML.

**Comment by jkhenning** [comment]
I'm not sure it's documented, but maybe the best thing to do is to simply add the option to provide a simple version as well (for example testing if the string is in "d.d" or "d.d.d" format and if so, append "=="?

**Comment by achaiah** [comment]
Ok I think your suggestion would work. Please take a look at the regex that I added.

**Comment by achaiah** [comment]
Ugh..lol yeah, the regex gets more complicated but I think I got it

**Pull request merged**
